package com.xiajue.browser.localwebbrowser.model.database.greenUtils;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xiajue.browser.localwebbrowser.model.bean.HomeListBean;
import com.xiajue.browser.localwebbrowser.model.bean.CollectionBean;
import com.xiajue.browser.localwebbrowser.model.bean.RemoveBean;

import com.xiajue.browser.localwebbrowser.model.database.greenUtils.HomeListBeanDao;
import com.xiajue.browser.localwebbrowser.model.database.greenUtils.CollectionBeanDao;
import com.xiajue.browser.localwebbrowser.model.database.greenUtils.RemoveBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeListBeanDaoConfig;
    private final DaoConfig collectionBeanDaoConfig;
    private final DaoConfig removeBeanDaoConfig;

    private final HomeListBeanDao homeListBeanDao;
    private final CollectionBeanDao collectionBeanDao;
    private final RemoveBeanDao removeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeListBeanDaoConfig = daoConfigMap.get(HomeListBeanDao.class).clone();
        homeListBeanDaoConfig.initIdentityScope(type);

        collectionBeanDaoConfig = daoConfigMap.get(CollectionBeanDao.class).clone();
        collectionBeanDaoConfig.initIdentityScope(type);

        removeBeanDaoConfig = daoConfigMap.get(RemoveBeanDao.class).clone();
        removeBeanDaoConfig.initIdentityScope(type);

        homeListBeanDao = new HomeListBeanDao(homeListBeanDaoConfig, this);
        collectionBeanDao = new CollectionBeanDao(collectionBeanDaoConfig, this);
        removeBeanDao = new RemoveBeanDao(removeBeanDaoConfig, this);

        registerDao(HomeListBean.class, homeListBeanDao);
        registerDao(CollectionBean.class, collectionBeanDao);
        registerDao(RemoveBean.class, removeBeanDao);
    }
    
    public void clear() {
        homeListBeanDaoConfig.clearIdentityScope();
        collectionBeanDaoConfig.clearIdentityScope();
        removeBeanDaoConfig.clearIdentityScope();
    }

    public HomeListBeanDao getHomeListBeanDao() {
        return homeListBeanDao;
    }

    public CollectionBeanDao getCollectionBeanDao() {
        return collectionBeanDao;
    }

    public RemoveBeanDao getRemoveBeanDao() {
        return removeBeanDao;
    }

}
